paths:
  /alert:
    get:
      tags:
        - Alert
      summary: 알림 조회
      parameters:
        - name: userId
          in: query
          required: true
          description: 유저 Id
          example: 99
      responses:
        "200":
          description: 알림 생성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
          data:
            type: object
            example:
              {
                "alert_id": 9,
                "alert_status": 0,
                "alert_date": "2025-05-25 15:30:00",
                "alert_type": "original",
                "link":{
                    "id": 5,
                    "title": "Link 2",
                    "memo": "link 2 memo"
                }
              }
        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
