paths:
  /alert/unconfirmed-exists:
    get:
      tags:
        - Alert
      summary: 미확인 알림 여부 
      responses:
        "200":
          description: 미확인 알림 여부 API 성공!
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "success!"
              result:
                type: object
                example:
                  {
                     "uncomfirmed-alert": true
                  }
        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
