paths:
  /link/get_links/{zip_id}:
    get:
      tags:
        - Link
      summary: 링크 데이터 가져오기
      description: |
          만약 조건(zip, user의 ID값)에 해당하는 값이 없더라도 오류 처리 하지 않고 빈 배열을 반환합니다.
          응답 데이터 중 thumb값은 해당 사이트에서 따로 설정해둔 이미지가 없을 경우 null로 설정됩니다. 
      parameters:
        - name: zip_id
          in: path
          description: '링크가 속한 zip의 id값을 파라미터로 넘겨야 합니다.'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - name: tag
          in: query
          description: 'tag값이 link인 경우 link인 값들만 호출, text인 경우 text인 값들만 호출, 설정하지 않은 경우 모든 링크 데이터를 호출'
          required: false
          schema:
            type: string
            example: 'link'
      responses:
        200:
          description: 링크 데이터가 성공적으로 호출된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    zip_id:
                      type: integer
                    user_id:
                      type: integer
                    title:
                      type: string
                    url:
                      type: string
                    text:
                      type: string
                    memo:
                      type: string
                    tag:
                      type: string
                    alert_date:
                      type: string
                      format: date-time
                    thumb:
                      type: string
                    like:
                      type: integer
                    visit:
                      type: integer
                    visit_date:
                      type: string
                      format: date-time
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
              
  /link/get_link/{link_id}:
    get:
      tags:
        - Link
      summary: 링크 ID로 링크 데이터 가져오기
      description: |
        특정 링크 ID에 대한 링크 데이터를 가져옵니다.
        요청된 링크가 존재하지 않는 경우 404 Not Found 상태 코드를 반환합니다.
      parameters:
        - name: link_id
          in: path
          description: '링크 ID 값을 경로 매개변수로 전달합니다.'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: 링크 데이터가 성공적으로 호출된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  id:
                    type: integer
                  zip_id:
                    type: integer
                  user_id:
                    type: integer
                  title:
                    type: string
                  url:
                    type: string
                  text:
                    type: string
                  memo:
                    type: string
                  tag:
                    type: string
                  alert_date:
                    type: string
                    format: date-time
                  thumb:
                    type: string
                  like:
                    type: integer
                  visit:
                    type: integer
                  visit_date:
                    type: string
                    format: date-time
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
        404:
          description: 링크를 찾을 수 없음
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: LINK002
              message:
                type: string
                example: "해당 링크를 찾을 수 없습니다."
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /link/add:
    post:
      tags:
        - Link
      summary: link 데이터(text 포함) 추가 생성
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: 링크를 생성하기 위한 데이터
          required: true
          schema:
            type: object
            properties:
              zip_id:
                type: integer
                example: 99
              title:
                type: string
                example: "Link Title"
              text:
                type: string
                example: "This is some text"
              url:
                type: string
                example: "https://www.example.com"
              memo:
                type: string
                example: "This is a memo"
              alert_date:
                type: string
                format: date-time
                example: "2023-01-01T12:00:00Z"
      responses:
        201:
          description: 링크가 성공적으로 생성된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "create success!"
              result:
                type: object
                properties:
                  link_id:
                    type: integer
                    example: 123
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
              result:
                type: object
                additionalProperties: false
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
              result:
                type: object
                additionalProperties: false


  /link/visit/{link_id}:
    patch:
      tags:
        - Link
      summary: 링크 방문 수 및 방문 날짜 업데이트
      parameters:
        - name: link_id
          in: path
          description: '방문 수를 업데이트할 링크의 ID'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: 방문 수 및 방문 날짜가 성공적으로 업데이트된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  link_id:
                    type: integer
                  visit:
                    type: integer
                  visit_date:
                    type: string
                    format: date-time
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /link/update_like/{link_id}:
    patch:
      tags:
        - Link
      summary: 링크 좋아요 상태 업데이트
      parameters:
        - name: link_id
          in: path
          description: '좋아요 상태를 업데이트할 링크의 ID'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: 좋아요 상태가 성공적으로 업데이트된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  link_id:
                    type: integer
                  like:
                    type: integer
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /link/move/{link_id}/{new_zip_id}:
    patch:
      tags:
        - Link
      summary: 링크의 Zip 이동
      parameters:
        - name: link_id
          in: path
          description: 'Zip을 이동할 링크의 ID'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
        - name: new_zip_id
          in: path
          description: '이동할 Zip의 ID'
          required: true
          schema:
            type: integer
            format: int32
            example: 2
      responses:
        200:
          description: Zip이 성공적으로 업데이트된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  link_id:
                    type: integer
                  new_zip_id:
                    type: integer
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다"
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /link/modify/{link_id}:
    patch:
      tags:
        - Link
      summary: 링크 지정하여 내용 수정
      consumes:
        - application/json
      parameters:
        - in: path
          name: link_id
          description: 수정할 링크의 ID
          required: true
          schema:
            type: integer
            example: 123
        - in: body
          name: body
          description: 수정할 링크의 제목, 텍스트, 메모, 알림 날짜 등의 정보를 포함합니다.
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
                example: "Updated Title"
              text:
                type: string
                example: "Updated Text Content"
              memo:
                type: string
                example: "Updated Memo"
              alert_date:
                type: string
                format: date
                example: "2024-08-15"
      responses:
        200:
          description: 링크 정보를 성공적으로 수정했습니다.
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  title:
                    type: string
                    example: "Updated Title"
                  text:
                    type: string
                    example: "Updated Text Content"
                  memo:
                    type: string
                    example: "Updated Memo"
                  alert_date:
                    type: string
                    format: date
                    example: "2024-08-15"
                  message:
                    type: string
                    example: "123번 링크 내용을 성공적으로 수정하였습니다."
        400:
          description: 잘못된 요청입니다.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다."
        404:
          description: 수정할 링크를 찾을 수 없습니다.
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: NOT_FOUND
              message:
                type: string
                example: "수정된 링크 데이터가 없습니다."
        500:
          description: 서버 에러입니다.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /link/delete/{link_id}:
    delete:
      tags:
        - Link
      summary: 링크 삭제
      parameters:
        - name: link_id
          in: path
          description: '삭제할 링크의 ID'
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: 링크가 성공적으로 삭제된 경우
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "1개의 링크 데이터를 성공적으로 삭제하였습니다."
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다."
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."