paths:
  /notice:
    get:
      tags:
        - "Notice"
      summary: "전체 공지사항 목록 가져오기"
      description: "전체 공지사항 목록을 가져옵니다."
      responses:
        200:
          description: "공지사항 목록을 성공적으로 가져온 경우"
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  notice_data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
        400:
          description: "잘못된 요청"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "서버 에러"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /notice/{notice_id}:
    get:
      tags:
        - "Notice"
      summary: "공지사항 ID로 공지사항 가져오기"
      description: "특정 공지사항 ID에 대한 공지사항 데이터를 가져옵니다."
      parameters:
        - name: notice_id
          in: path
          description: "공지사항 ID 값을 경로 매개변수로 전달합니다."
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: "공지사항 데이터가 성공적으로 호출된 경우"
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        400:
          description: "잘못된 요청"
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "공지사항을 찾을 수 없음"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "서버 에러"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /notice/add:
    post:
      tags:
        - "Notice"
      summary: "새 공지사항 추가"
      description: "새로운 공지사항을 추가합니다."
      parameters:
        - name: body
          in: body
          description: "추가할 공지사항 데이터"
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
      responses:
        200:
          description: "공지사항이 성공적으로 추가된 경우"
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  notice_id:
                    type: integer
        400:
          description: "잘못된 요청"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "서버 에러"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /notice/delete/{notice_id}:
    delete:
      tags:
        - "Notice"
      summary: "공지사항 삭제"
      description: "특정 공지사항을 삭제합니다."
      parameters:
        - name: notice_id
          in: path
          description: "공지사항 ID 값을 경로 매개변수로 전달합니다."
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: "공지사항이 성공적으로 삭제된 경우"
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "성공적으로 삭제되었습니다."
              result:
                type: string
                example: "1개의 공지사항 데이터를 성공적으로 삭제하였습니다."
        400:
          description: "잘못된 요청"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "서버 에러"
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  ErrorResponse:
    type: object
    properties:
      status:
        type: integer
        example: 400
      isSuccess:
        type: boolean
        example: false
      code:
        type: integer
        example: COMMON001
      message:
        type: string
        example: "잘못된 요청입니다"