paths:
  /search:
    get:
      tags:
        - Search
      summary: 링크 검색
      description: |
        키워드를 입력하여 title 혹은 text에 포함되는 링크나 텍스트를 검색
      parameters:
        - in: query
          name: keyword
          required: true
          type: string
          description: 검색 키워드
      responses:
        200:
          description: 링크 검색 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        link:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            url:
                              type: string
                            tag:
                              type: string
                            thumbnail:
                              type: string
                            like:
                              type: integer
                            createdAt:
                              type: string
                        zip:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            color:
                              type: string

        400:
          description: 잘못된 검색어 입력(아무것도 입력하지 않았을때)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH001"
              message:
                type: string
                example: "잘못된 검색어 입니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        404:
          description: 검색결과가 없습니다.
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH002"
              message:
                type: string
                example: "검색결과가 없습니다."
        
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
        
  /search/logs:
    get:
      tags:
        - Search
      summary: 검색기록 조회
      description: |
        검색했던 모든 기록 최대 15개까지 조회합니다
      responses:
        200:
          description: 검색 기록 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  searchLogs:
                    type: array
                    items:
                      type: string
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        404:
          description: 검색기록이 없습니다.
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH003"
              message:
                type: string
                example: "검색기록이 없습니다."
        
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
  
    delete:
      tags:
        - Search
      summary: 특정 검색 기록 삭제
      description: |
        특정 검색 기록을 삭제합니다.
      parameters:
        - in: query
          name: keyword
          required: true
          type: string
          description: 검색기록 키워드
      responses:
        200:
          description: 특정 검색기록 삭제 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "delete success!"
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "해당 검색기록이 삭제되었습니다."
        
        400:
          description: 잘못된 검색어 입력(아무것도 입력하지 않았을때)
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH001"
              message:
                type: string
                example: "잘못된 검색어 입니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        404:
          description: 검색기록이 없습니다.
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH003"
              message:
                type: string
                example: "검색기록이 없습니다."
        
        500:
          description: 서버 에러(없는 검색기록 입력시)
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /search/logs/all:
    delete:
      tags:
        - Search
      summary: 모든 검색 기록 삭제
      description: |
        모든 검색 기록을 삭제
      responses:
        200:
          description: 모든 검색 기록 삭제 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "모든 검색기록이 삭제되었습니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."         
