paths:
  /search:
    get:
      tags:
        - Search
      summary: 링크 검색
      description: |
        키워드를 입력하여 title 혹은 text에 포함되는 링크나 텍스트를 검색
      parameters:
        - in: query
          name: keyword
          required: true
          type: string
          description: 검색 키워드
      responses:
        200:
          description: 링크 검색 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              result:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    zip_id:
                      type: integer
                    user_id:
                      type: integer
                    title:
                      type: string
                    url:
                      type: string
                    text:
                      type: string
                    memo:
                      type: string
                    tag:
                      type: string
                    alert_date:
                      type: string
                      format: date-time
                    thumb:
                      type: string
                    like:
                      type: integer
                    visit:
                      type: integer
                    visit_date:
                      type: string
                      format: date-time
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time

        400:
          description: 잘못된 검색어 입력(아무것도 입력하지 않았을때)
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "SEARCH001"
              message:
                type: string
                example: "잘못된 검색어 입니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        404:
          description: 검색결과가 없습니다.
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "SEARCH002"
              message:
                type: string
                example: "검색결과가 없습니다."
        
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
        

  
          
