paths:
  /user:
    post:
      tags:
        - User
      summary: 사용자 회원가입
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              nickname:
                type: string
                example: 'nickname'
      responses:
        "200":
          description: 사용자 회원가입 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
            data:
              type: object
              example:
                {
                  "user":
                    {
                      "id": "1",
                      "email": "example@example.com",
                      "createdAt": "2024-07-15"
                    }
                }
        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/{userId}:
    get:
      tags:
        - User
      summary: 사용자 정보 조회
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
          description: 사용자 Id
      responses:
        "200":
          description: 사용자 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example:
                  {
                    "user":
                    {
                      "userId": "1",
                      "nickname": "example",
                      "createdAt": "2024-07-15"
                    }
                  }
        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.