paths:
  /zips:
    post:
      tags:
        - Zip
      summary: Zip 생성
      description: |
        Zip의 title 과 color을 입력받아 Zip 생성 진행
      parameters:
      - in: body
        name: body
        description: Zip의 제목과 색 데이터
        required: true
        schema:
          type: object
          properties:
            title:
              type: string
              example: 'example-title'
            color:
              type: string
              example: 'example-color'
      responses:
        200:
          description: Zip 생성 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "create success!"
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "알림이 생성되었습니다"
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON001"
              message:
                type: string
                example: "잘못된 요청입니다"
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."

        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
    get:
      tags:
        - Zip
      summary: 사용자의 Zip 조회
      description: |
        사용자의 Zip을 정렬기준에 따라 정렬하여 조회
      parameters:
      - in: query
        name: sort
        type: string
        default: latest
        enum: [latest, earliest, alphabet, visit]
        description: 정렬 기준
        required: true
      responses:
        200:
          description: 조회 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: "success!"
              result:
                type: object
                properties:
                  zips:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: integer
                          example: 99
                        zip_id:
                          type: integer
                          example: 113
                        title:
                          type: string
                          example: "example-title"
                        color:
                          type: string
                          example: "example-color"
                        link_count:
                          type: integer
                          example: 5
        400:
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON001"
              message:
                type: string
                example: "잘못된 요청입니다"
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."

        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
    patch:
      tags:
        - Zip
      summary: 사용자의 Zip 수정
      description: |
        사용자의 Zip의 title과 color 수정
      parameters:
        - in: body
          name: body
          description: Zip의 제목과 색 데이터
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 112
              title:
                type: string
                example: "example-title"
              color:
                type: string
                example: "example-color"
      responses:
        200:
          description: Zip 수정 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: update success!
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "99 zip이 수정되었습니다."

        400:
          description: Default Zip 수정 불가
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "ZIP001"
              message:
                type: string
                example: "Default Zip은 수정이 불가합니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."

        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
  /zips/{zip_id}:  
    delete:
      tags:
          - Zip
      summary: 사용자의 Zip 삭제
      description: |
        사용자의 Zip 삭제
      parameters:
        - in: path
          name: zip_id
          description: Zip id
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 112
      responses:
        200:
          description: Zip 삭제 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: "2000"
              message:
                type: string
                example: success!
              result:
                type: object
                properties:
                  message:
                    type: string
                    example: "99 zip이 삭제되었습니다."
        400:
          description: Default Zip 삭제 불가
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "ZIP002"
              message:
                type: string
                example: "Default Zip은 삭제가 불가합니다."
        
        401:
          description: 권한 오류
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "TOKEN003"
              message:
                type: string
                example: "유효하지 않은 토큰입니다."
        
        500:
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: "COMMON000"
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
